language: python

python:
  - 3.6
  - 3.7
  - 3.8

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y graphviz
  - pip install --upgrade pip setuptools
  - pip install -r requirements.txt
  - pip install .

script:
  - cd tests/
  - nosetests --with-coverage --cover-package=promela

after_success:
  - coveralls
